Basic Design Completed
Improwised/ip-address-tracker pull request #6
Opened 2022-02-15 13:49 UTC by Payal17122000

2022-02-16 05:29 UTC, codesnail21 commented on pages/index.vue
> +    // this.$router.push("/payal")
remove if it is not necessary

2022-02-16 05:30 UTC, codesnail21 requested changes
remove the un-necessary comment

2022-02-17 07:24 UTC, codesnail21 approved these changes

2022-02-17 10:18 UTC, zeelrupapara approved these changes

2022-02-17 10:18 UTC, zeelrupapara commented on pages/payal/index.vue
> +  <div class="container d">
whay form is out side a componant

2022-02-17 11:46 UTC, merged